### PR TITLE
Enable Power Profile Management

### PR DESCRIPTION
**Pull request by SubhadeepJasu**
Enable Automatic/Manual power management from power switchboard plug.
- [x] Make mode buttons to change management mode
- [x] Make power management mode icons
- [x] Use Free desktop power profiles daemon
- [ ] ~~Make automatic power management logic~~ (Out of scope for now, but it can be implemented later)

### CODE REVIEW

**Comment by SubhadeepJasu** [comment]
Current progress on it.
- Daemon works as a service on root.
- It gets a list of users who are logged in and uses the first user to connect to that dbus session.
- Currently only supports CPU modes
- Currently only supports the two manual modes "Power Saver" and "High Performance"

Screenshot from 2021-07-18 09-34-56
Screenshot from 2021-07-18 09-35-37

**Comment by cassidyjames** [comment]
@SubhadeepJasu regarding the daemon, it looks like the upstream solution is https://gitlab.freedesktop.org/hadess/power-profiles-daemon. Would it be possible to depend on that?

**Comment by SubhadeepJasu** [comment]
I would wanna. They are providing manual power management. Not sure if they want to do automatic as well. If not then we have to do something about that.

**Comment by SubhadeepJasu** [comment]
They are providing two use cases: powersaver and performance. I think for the 3rd use case we can merge a part of my code about automatic mode into either the indicator or settings daemon. That will allow us to use freedesktop ppm along with my logic for an auto mode.

**Comment by cassidyjames** [comment]
@SubhadeepJasu it would be worth chatting with upstream first before doing our own automatic mode downstream; less code to maintain ourselves is almost always good—plus other desktops can benefit from our contributions.

**Comment by SubhadeepJasu** [comment]
I'll open an issue on their repo to discuss the need for an automatic mode and possible ways to pull it off.

**Comment by SubhadeepJasu** [comment]
We have an open issue on their repo: https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/issues/42

**Comment by SubhadeepJasu** [comment]
Nope, they recommend doing this on our end. An automatic mode upstream is out of scope. According to the maintainer, the whole battery, load and thermal monitoring + automatic/intelligent scaling is something that the DE should implement. Also He said that its not something that can be called "upstream" :-/

What do you suggest?

**Comment by cassidyjames** [comment]
@SubhadeepJasu it sounds like to start we would offer Power Saver, Balanced, and High Performance modes and that would be in line with the power-profiles-daemon. In the future we could offer smarter configuration and switching of modes, like when someone plugs in or unplugs power, when the battery is low, etc. But for now just being able to configure the power-profiles-daemon sounds like a useful improvement.

>Also He said that its not something that can be called "upstream" :-/

I think they just meant that implementing it in that project whether upstream or in a fork didn't make sense, and doesn't realize that we're considering the daemon an upstream project. Just a miscommunication. :smile:

**Comment by SubhadeepJasu** [comment]
Gotcha

**Comment by SubhadeepJasu** [comment]
This has to wait, for some time. Because I got some urgent work this week.

**Comment by SubhadeepJasu** [comment]
Now it works with power profile manager 

image

image

image

**Comment by jhaygood86** [comment]
I would add a label to the buttons.

**Comment by SubhadeepJasu** [comment]
Yeah, I'll change the styling to match the other similar radio button elements in the UI.

**Comment by SubhadeepJasu** [comment]
I ended up not changing it much, but I have added labels instead of the tooltips.

Screenshot from 2021-09-12 21-16-22

**Comment by tomaswarynyca** [comment]
@SubhadeepJasu It should be thought about how to integrate it into the new design #194

**Comment by SubhadeepJasu** [comment]
It only applies to the behavior section. I would suggest merging that pr first which would make it easier to merge this one appropriately.

**Review by meisenzahl — DISMISSED** [review]

**Comment by danrabbit** [comment]
Noting here that it looks like GNOME Settings Daemon includes a setting for automatically enabling power saving profile on low battery at `org.gnome.settings-daemon.plugins.power power-saver-profile-on-low-battery`.

Targeting this also to OS 7 since we have power profiles daemon installed by default now

**Review by danrabbit — APPROVED** [review]
This does the thing, so I'm inclined to merge and iterate while we're at the beginning of the cycle. Nice work!

**Comment by SubhadeepJasu** [comment]
Awesome! We can later have a automatic toggle or a fourth button for it based on what the designers decide.

**Pull request merged**
