### PR TITLE
MainView: use Gtk.Dropdown for power button behavior

### PR DESCRIPTION
**Pull request by danirabbit**
This doesn't need to be a whole widget for a simple dropdown. Fixes deprecation warning and set mnemonic widget for the screen reader

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
The label is misaligned relative to the others.  Also the width of the drop down changes when selecting the last item, affecting the window width.

Screenshot from 2024-02-10 09 59 13

**Comment by leolost2605** [comment]
I just came across the same dropdown resizing issue in another part in settings. A possible solution would be something like this:
```
var size_group = new Gtk.SizeGroup (HORIZONTAL);
size_group.add_widget (drop_down.get_first_child ()); //The toggle button
size_group.add_widget (drop_down.get_last_child ().get_first_child ()); //The popover
```
Would this be accepted?

**Comment by danirabbit** [comment]
Yeah I didn't make a huge effort here because the alignment of this whole view is pretty fucky so I'll need to come back later after everything is updated to fix things. But yeah I think a sizegroup is needed here

**Comment by danirabbit** [comment]
@jeremypw reverted layout changes! I'll deal with those as a group in another branch

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
