### PR TITLE
Port to Gtk4

### PR DESCRIPTION
**Pull request by ZenitsuDev**
Goes with https://github.com/elementary/switchboard/pull/231

Blocked by:
- [x] Depends on https://github.com/elementary/switchboard/pull/231

Todo: 
- [x] Test on device with battery

### CODE REVIEW

**Comment by lenemter** [comment]
I had to change the way authentication works. Here permission is asked on opening combobox. Trying to replicate the way auth in master works gives this:
image

**Comment by jeremypw** [comment]
There are some visual glitches at the moment when using `gtk4` which may not be to do with code you have written. Either from upstream or maybe Gala.  It would be better to maintain the behaviour approved for Gtk3 if at all possible. I'll have a look into it.

**Comment by jeremypw** [comment]
CI failing because of upstream issue.  See https://github.com/elementary/docker/issues/25

**Review by jeremypw — COMMENTED** [review]
@lenemter I think I have restored the behaviour of the Gtk3 version.  It works for me - does it for you?

**Comment by lenemter** [comment]
@jeremypw Yes, it does. But I found a big issue in both gtk3 and gtk4 versions. While authentication dialog is open, focus settings window using alt+tab or click and wait, after a short time "Not responding" window starts pop up every 5 seconds, even after you close auth dialog and power plug itself

**Comment by lenemter** [comment]
I found the exact same issue in gtk3 locale plug

**Comment by jeremypw** [comment]
As the same problem occurs in more than one plug I am going to merge this PR and raise a separate issue.

**Review by danrabbit — APPROVED** [review]
Let's go :tada:

**Pull request merged**
