### PR TITLE
PowerModeButton: cleanup

### PR DESCRIPTION
**Pull request by danirabbit**
Screenshot from 2024-02-08 15 47 46

### CODE REVIEW

**Comment by lenemter** [comment]
@danirabbit Can you resolve conflicts please?

**Comment by danirabbit** [comment]
@lenemter done!

**Review by lenemter — APPROVED** [review]
Code looks good but IMHO "Power Mode" label really needs some spacing.

**Comment by danirabbit** [comment]
@lenemter yeah I'm gonna end up moving this around quite a bit more I think. this whole plug is kinda messy and has a lot of odd stuff going on 😅

**Pull request merged**
