### PR TITLE
LidCloseActionComboBox: use Gtk.Dropdown

### PR DESCRIPTION
**Pull request by danirabbit**

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
Opening the combobox results in an authentication dialog appearing beneath the dropdown:
Screenshot from 2024-02-19 11 53 49


Focusing another window - the dropdown remains on top:
Screenshot from 2024-02-19 11 53 57

Pressing the Close Window button with the dropdown showing results in the "Not Responding" warning.
The dropdown should presumably close before showing the dialog?

**Comment by jeremypw** [comment]
Note: Tested on OS8 in a Pantheon X session.

**Comment by danirabbit** [comment]
@jeremypw ah yeah okay did a separate branch since this also affects main: https://github.com/elementary/switchboard-plug-power/pull/260

**Comment by jeremypw** [comment]
@danirabbit Please resolve conflict, thanks.

**Comment by jeremypw** [comment]
@danirabbit Sorry - more conflicts now.

**Comment by danirabbit** [comment]
@jeremypw fixed!

**Review by jeremypw — APPROVED** [review]
All looks good now!

**Pull request merged**
