### PR TITLE
MainView: justify layout, space between sections

### PR DESCRIPTION
**Pull request by danirabbit**
Try to make this layout a bit less wacky and easier to maintain:
* Put sections in their own grids and double space between sections
* Justify layout of widgets and labels
* Set mnemonic widget where possible (Some comboboxes will need this fixed when ported to dropdown)
* Put infobar by the lid settings

Screenshot from 2024-02-13 11 34 43@2x

### CODE REVIEW

**Comment by jeremypw** [comment]
@danirabbit Could you resolve the conflict please?

**Comment by danirabbit** [comment]
@jeremypw done!

**Review by jeremypw — CHANGES_REQUESTED** [review]
When the Lid Close behaviour is changed, the authentication dialog appears (behind the dropdown which remains open, if app running in centre of screen) and the whole system hangs. A forced reboot is then required.

**Comment by danirabbit** [comment]
@jeremypw thats fixed in #258 :)

**Review by jeremypw — COMMENTED** [review]
Code and appearance look good, but I am getting a system hang (unresponsive to keyboard and mouse) when the authentication dialog appears after selecting a lid close option.  Not sure whether due to this PR though.

**Comment by danirabbit** [comment]
@jeremypw this branch only touches layout code. There are no functional changes in this branch whatsoever

**Review by jeremypw — APPROVED** [review]
Approving on the basis that it only affects layout, not function.

**Pull request merged**
